package:
  name: dfndarray
  version: 0.0.1

requirements:
  build:
    - python=2.7
    #- swig # todo: use conda SWIG (currently bugged)
    - numpy
  run:
    - python=2.7
    - numpy

source:
  git_url: https://github.com/dfroger/dfndarray

build:
  number: 0
  binary_relocation: false

about:
  home: https://github.com/dfroger/dfndarray
  license: GPL
