package:
  name: dfndarray
  version: 0.0.0

source:
  git_url: https://github.com/dfroger/dfndarray

build:
  number: 1
  binary_relocation: false

about:
  home: https://github.com/dfroger/dfndarray
  license: GPL
