package:
  name: dfndarray
  version: 0.1.0

requirements:
  build:
    - python 2.7*
    - swig-python
    - numpy
  run:
    - python 2.7*
    - numpy

source:
  git_url: https://github.com/dfroger/dfndarray

build:
  number: 1
  binary_relocation: true

about:
  home: https://github.com/dfroger/dfndarray
  license: GPL
