package:
  name: dfndarray
  version: 0.2.1

requirements:
  build:
    - python
    - swig
    - numpy
  run:
    - python
    - numpy

source:
  path: ..
  #fn: dfndarray-0.2.1.tar.gz
  #url: https://github.com/dfroger/dfndarray/archive/v0.2.1.tar.gz

build:
  number: 0 # [linux]
  number: 1 # [osx]
  binary_relocation: true

about:
  home: https://github.com/dfroger/dfndarray
  license: GPL
  summary: Minimalist C++ multidimensional array implementation.
