package:
  name: dfndarray
  version: 0.2.2

requirements:
  build:
    - python
    - swig
    - numpy
  run:
    - python
    - numpy

source:
  fn: dfndarray-0.2.2.tar.gz
  url: https://github.com/dfroger/dfndarray/archive/0.2.2.tar.gz

build:
  number: 0
  binary_relocation: true

about:
  home: https://github.com/dfroger/dfndarray
  license: GPL
  summary: Minimalist C++ multidimensional array implementation.
