package:
  name: dfndarray
  version: 0.2.1

requirements:
  build:
    - python 2.7*
    - swig-python
    - numpy
  run:
    - python 2.7*
    - numpy

source:
  fn: dfndarray-0.2.1.tar.gz
  url: https://github.com/dfroger/dfndarray/archive/v0.2.1.tar.gz

build:
  number: 0
  binary_relocation: true

about:
  home: https://github.com/dfroger/dfndarray
  license: GPL
