package:
  name: dfndarray
  version: 0.2.0

requirements:
  build:
    - python 2.7*
    - swig-python
    - numpy
  run:
    - python 2.7*
    - numpy

source:
  path: ..
  #fn: dfndarray-0.2.0.tar.gz
  #url: https://github.com/dfroger/dfndarray/archive/0.2.0.tar.gz

build:
  number: 0
  binary_relocation: true

about:
  home: https://github.com/dfroger/dfndarray
  license: GPL
