#!/usr/bin/env python

from os.path import join

VERSION='0.1.0'

top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_cxx python')

    opt.add_option('--python-bindings', action='store_true', default=False,
            help='Generate Python bindings using SWIG (default: False)')

    opt.add_option('--enable-shared', action='store_true', default=False,
            help='Build shared library. --python-bindings automatically '
                 'activates --enable-shared (default: False)')

def configure(conf):
    conf.load('compiler_cxx')

    conf.env.append_value('CFLAGS', ['-mmacosx-version-min=10.7'])
    conf.env.append_value('CXXFLAGS', ['-mmacosx-version-min=10.7','-stdlib=libc++'])
    conf.env.append_value('LDFLAGS', ['-mmacosx-version-min=10.7','-stdlib=libc++'])

    conf.env.ENABLE_SHARED = conf.options.enable_shared

    if conf.options.python_bindings:
        conf.env.PYTHON_BINDINGS = True
        conf.load('python')
        conf.check_python_version((2,4,2))
        conf.check_python_headers()

        conf.load('swig')
        if conf.check_swig_version() < (1,2,27):
            conf.fatal('this swig version is too old')

        import numpy
        numpy_inc = numpy.get_include()

        #python_inc = join(miniconda_dir,'include','python2.7')
        #conf.env.prepend_value('INCLUDES', [python_inc,numpy_inc])
        conf.env.prepend_value('INCLUDES', [numpy_inc])
        conf.env.ENABLE_SHARED = True
    else:
        conf.env.PYTHON_BINDINGS = False

def build(bld):
    args = {
        'features' : 'cxx',
        'source' : 'dfndarray.cxx',
        'target' : 'dfndarray',
        'includes' : '.',
        'export_includes' : '.',
        'vnum' : VERSION,
        'name' : 'dfndarray',
        'cxxflags' : ['-O3','-DNDEBUG'],
    }

    bld.stlib(**args)
    if bld.env.ENABLE_SHARED:
        bld.shlib(**args)

    bld.install_files('${PREFIX}/include', 'dfndarray.hxx dfndarray.txx')
    bld.install_files('${PREFIX}/lib', 'libdfndarray.a')

    if bld.env.PYTHON_BINDINGS:
        bld(
            features = 'cxx cxxshlib pyext',
            source = 'dfndarray.i',
            target = '_dfndarray',
            swig_flags = '-c++ -python',
            includes = '.',
            vnum = VERSION,
            use  = 'dfndarray',
            cxxflags = ['-g','-O3', '-DDFNDARRAY_RUNTIME_CHECK'],
        )
        python_site_package = '${PREFIX}/lib/python%s/site-packages' % bld.env['PYTHON_VERSION']
        bld.install_files(python_site_package, 'dfndarray.py')
