#!/usr/bin/env python

from os.path import join

VERSION='0.1.0'

top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_cxx')

    opt.add_option('--python-bindings', action='store_true', default=False,
            help='Generate Python bindings using SWIG (default: False)')

def configure(conf):
    conf.load('compiler_cxx')

    if conf.options.python_bindings:
        conf.env.PYTHON_BINDINGS = True
        conf.load('python')
        conf.check_python_version((2,4,2))
        conf.check_python_headers()

        conf.load('swig')
        if conf.check_swig_version() < (1,2,27):
            conf.fatal('this swig version is too old')

        import numpy
        numpy_inc = numpy.get_include()

        #python_inc = join(miniconda_dir,'include','python2.7')
        #conf.env.prepend_value('INCLUDES', [python_inc,numpy_inc])
        conf.env.prepend_value('INCLUDES', [numpy_inc])
    else:
        conf.env.PYTHON_BINDINGS = False

def build(bld):
    bld(
        features = 'cxx cxxshlib',
        source = 'dfndarray.cxx',
        target = 'dfndarray',
        includes = '.',
        export_includes = '.',
        vnum = VERSION,
        name = 'dfndarray',
        cxxflags = ['-O3','-DNDEBUG'],
    )

    bld.install_files('${PREFIX}/include', 'dfndarray.hxx dfndarray.txx')

    if bld.env.PYTHON_BINDINGS:
        bld(
            features = 'cxx cxxshlib pyext',
            source = 'dfndarray.i',
            target = '_dfndarray',
            swig_flags = '-c++ -python',
            includes = '.',
            vnum = VERSION,
            use  = 'dfndarray',
            cxxflags = ['-g','-O3', '-DDFNDARRAY_RUNTIME_CHECK'],
        )
        python_site_package = '${PREFIX}/lib/python%s/site-packages' % bld.env['PYTHON_VERSION']
        bld.install_files(python_site_package, 'dfndarray.py')
